language: c
sudo: false
git:
  depth: false
  quiet: true
env:
  global:
     - PRETTYNAME="Neosensory SDK for Adafruit Bluefruit"

# Generate and deploy documentation
after_success:
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
  - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
