sudo: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
