sudo: false

branches:
  except:
    - gh-pages

addons:
  apt:
    packages:
      - doxygen

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  committer_from_gh: true
